#!/usr/bin/env python3
"""Generate seed.sql for OnePlace with 28 real NL businesses.
Actual DB schema used - verified against live database."""

import uuid, json, os

DAY_MAP = {"mon": 0, "tue": 1, "wed": 2, "thu": 3, "fri": 4, "sat": 5, "sun": 6}

def esc(s):
    if s is None: return "NULL"
    return "'" + str(s).replace("'", "''") + "'"

def sql_arr(arr):
    if not arr: return "NULL"
    return "ARRAY[" + ",".join(esc(x) for x in arr) + "]::text[]"

def sql_jb(d):
    if not d: return "'{}'::jsonb"
    return "'" + json.dumps(d).replace("'", "''") + "'::jsonb"

def parse_address(addr):
    """Parse '80 Brookfield Rd, Mount Pearl, NL A1E 3T9, Canada' into parts."""
    if not addr:
        return (None, None, None, None, "Canada")
    parts = [p.strip() for p in addr.split(",")]
    line1 = parts[0] if len(parts) > 0 else None
    city = parts[1] if len(parts) > 1 else None
    province = parts[2] if len(parts) > 2 else None
    postal = parts[3] if len(parts) > 3 else None
    country = parts[-1] if len(parts) > 3 else "Canada"
    return (line1, city, province, postal, country)

def hours_sql(biz_var, hours):
    lines = []
    for dk in ["mon","tue","wed","thu","fri","sat","sun"]:
        day_num = DAY_MAP[dk]
        o, c, closed = hours[dk]
        if closed:
            lines.append(f"SELECT gen_random_uuid(), {biz_var}, {day_num}, NULL, NULL, true, now() FROM biz")
        else:
            lines.append(f"SELECT gen_random_uuid(), {biz_var}, {day_num}, '{o}'::time, '{c}'::time, false, now() FROM biz")
    return " UNION ALL ".join(lines)

def svcs_sql(biz_var, svcs):
    lines = []
    for s in svcs:
        name, desc, price, pt, dur, book = s
        dv = str(dur) if dur else "NULL"
        lines.append(
            f"SELECT gen_random_uuid(), {biz_var}, NULL, {esc(name)}, {esc(desc)}, {price}, 'CAD', {esc(pt)}, NULL, NULL, {dv}, {str(book).lower()}, true, '{{}}'::jsonb, now() FROM biz"
        )
    return " UNION ALL ".join(lines)

def know_sql(biz_var, items):
    lines = []
    for k in items:
        title, content, cat, pri = k
        lines.append(
            f"SELECT gen_random_uuid(), {biz_var}, {esc(title)}, {esc(content)}, {esc(cat)}, NULL, {pri}, true, '{{}}'::jsonb, now() FROM biz"
        )
    return " UNION ALL ".join(lines)

def photos_sql(biz_var, photos):
    lines = []
    for i, p in enumerate(photos):
        url, alt, is_cover = p
        lines.append(
            f"SELECT gen_random_uuid(), {biz_var}, {esc(url)}, {esc(alt)}, {i}, {str(is_cover).lower()}, now() FROM biz"
        )
    return " UNION ALL ".join(lines)

def prods_sql(biz_var, prods):
    lines = []
    for i, p in enumerate(prods):
        name, desc, pt, url, ptype = p
        lines.append(
            f"SELECT gen_random_uuid(), {biz_var}, {esc(name)}, {esc(desc)}, NULL, {esc(pt)}, NULL, NULL, 'CAD', NULL, {esc(url)}, {esc(ptype)}, {i}, true, now() FROM biz"
        )
    return " UNION ALL ".join(lines)


def main():
    data_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "business_data.json")
    with open(data_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    cats = data["categories"]
    businesses = data["businesses"]
    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "seed.sql")

    L = []
    L.append("-- OnePlace seed data: 28 real NL businesses")
    L.append("-- Generated by generate_seed.py")
    L.append("-- Safe for local dev: uses DELETE + re-INSERT")
    L.append("")

    # ── Clear existing data ────────────────────────────────
    L.append("DELETE FROM ai_knowledge_items WHERE business_id IN (SELECT id FROM businesses);")
    L.append("DELETE FROM ai_configurations WHERE business_id IN (SELECT id FROM businesses);")
    L.append("DELETE FROM business_hours WHERE business_id IN (SELECT id FROM businesses);")
    L.append("DELETE FROM business_services WHERE business_id IN (SELECT id FROM businesses);")
    L.append("DELETE FROM business_photos WHERE business_id IN (SELECT id FROM businesses);")
    L.append("DELETE FROM business_products WHERE business_id IN (SELECT id FROM businesses);")
    L.append("DELETE FROM business_categories WHERE business_id IN (SELECT id FROM businesses);")
    L.append("DELETE FROM businesses WHERE slug != '____never_match____';")
    L.append("")

    # ── Categories (no 'color' column in actual schema) ────
    parents = [c for c in cats if c[5] is None]
    children = [c for c in cats if c[5] is not None]

    L.append("-- Parent categories")
    L.append("INSERT INTO categories (id, name, slug, icon, image_url, parent_id, created_at)")
    L.append("VALUES")
    vals = []
    for c in parents:
        name, slug, icon, color, img, parent = c
        img_v = esc(img) if img else "NULL"
        vals.append(f"  (gen_random_uuid(), {esc(name)}, {esc(slug)}, {esc(icon)}, {img_v}, NULL, now())")
    L.append(",\n".join(vals))
    L.append("ON CONFLICT (slug) DO UPDATE SET")
    L.append("  name = EXCLUDED.name, icon = EXCLUDED.icon,")
    L.append("  image_url = COALESCE(EXCLUDED.image_url, categories.image_url),")
    L.append("  parent_id = EXCLUDED.parent_id;")
    L.append("")

    L.append("-- Child categories")
    L.append("INSERT INTO categories (id, name, slug, icon, image_url, parent_id, created_at)")
    L.append("VALUES")
    vals = []
    for c in children:
        name, slug, icon, color, img, parent = c
        img_v = esc(img) if img else "NULL"
        vals.append(
            f"  (gen_random_uuid(), {esc(name)}, {esc(slug)}, {esc(icon)}, {img_v}, (SELECT id FROM categories WHERE slug = {esc(parent)}), now())"
        )
    L.append(",\n".join(vals))
    L.append("ON CONFLICT (slug) DO UPDATE SET")
    L.append("  name = EXCLUDED.name, icon = EXCLUDED.icon,")
    L.append("  image_url = COALESCE(EXCLUDED.image_url, categories.image_url),")
    L.append("  parent_id = EXCLUDED.parent_id;")
    L.append("")

    # ── Businesses + related data ──────────────────────────
    L.append("-- Businesses")
    stats = {"biz": 0, "svcs": 0, "prods": 0, "know": 0, "photos": 0, "hrs": 0, "cat_link": 0}

    for b in businesses:
        name = b["name"]
        slug = b["slug"]
        line1, city, prov, postal, country = parse_address(b.get("address"))

        # metadata jsonb: tags + social_links + email
        meta = {}
        if b.get("tags"): meta["tags"] = b["tags"]
        if b.get("social_links"): meta["social_links"] = b["social_links"]
        if b.get("email"): meta["email"] = b["email"]

        L.append(f"-- {name}")
        L.append("DO $$ DECLARE b_id uuid; BEGIN")
        L.append("  INSERT INTO businesses (id, name, slug, description, phone, website_url,")
        L.append("    address_line_1, city, province, postal_code, country,")
        L.append("    latitude, longitude, founded_year, metadata, status,")
        L.append("    website_template, website_primary_color, website_accent_color, timezone, created_at)")
        L.append("  VALUES (")
        L.append("    gen_random_uuid(),")
        L.append(f"    {esc(name)},")
        L.append(f"    {esc(slug)},")
        L.append(f"    {esc(b['description'])},")
        L.append(f"    {esc(b.get('phone'))},")
        L.append(f"    {esc(b.get('website'))},")
        L.append(f"    {esc(line1)},")
        L.append(f"    {esc(city)},")
        L.append(f"    {esc(prov)},")
        L.append(f"    {esc(postal)},")
        L.append(f"    {esc(country)},")
        L.append(f"    {b['latitude']},")
        L.append(f"    {b['longitude']},")
        L.append(f"    {b.get('founded_year') or 'NULL'},")
        L.append(f"    {sql_jb(meta)},")
        L.append(f"    'active',")
        L.append(f"    {esc(b.get('website_template', 'classic'))},")
        L.append(f"    {esc(b.get('website_primary_color', '#3b82f6'))},")
        L.append(f"    {esc(b.get('website_accent_color', '#06b6d4'))},")
        L.append(f"    'America/St_Johns',")
        L.append(f"    '2025-01-01 00:00:00+00'::timestamptz")
        L.append("  ) RETURNING id INTO b_id;")
        L.append("")

        # Business-category link
        L.append(f"  INSERT INTO business_categories (business_id, category_id, is_primary, created_at)")
        L.append(f"  VALUES (b_id, (SELECT id FROM categories WHERE slug = {esc(b['category_slug'])}), true, now());")
        stats["cat_link"] += 1

        # Hours (day_of_week is smallint: 0=Mon..6=Sun)
        for dk in ["mon","tue","wed","thu","fri","sat","sun"]:
            day_num = DAY_MAP[dk]
            o, c, closed = b["hours"][dk]
            if closed:
                L.append(f"  INSERT INTO business_hours (id, business_id, day_of_week, is_closed, created_at) VALUES (gen_random_uuid(), b_id, {day_num}, true, now());")
            else:
                L.append(f"  INSERT INTO business_hours (id, business_id, day_of_week, opens_at, closes_at, is_closed, created_at) VALUES (gen_random_uuid(), b_id, {day_num}, '{o}'::time, '{c}'::time, false, now());")
        stats["hrs"] += 7

        # Services
        svcs = b.get("services", [])
        for s in svcs:
            name_s, desc_s, price_s, pt_s, dur_s, book_s = s
            if pt_s == "free":
                pt_s = "fixed"
                price_s = 0
            dur_v = str(dur_s) if dur_s else "NULL"
            price_v = price_s if price_s is not None else "NULL"
            L.append(f"  INSERT INTO business_services (id, business_id, name, description, price, currency, price_type, duration_minutes, booking_required, is_active, metadata, created_at) VALUES (gen_random_uuid(), b_id, {esc(name_s)}, {esc(desc_s)}, {price_v}, 'CAD', {esc(pt_s)}, {dur_v}, {str(book_s).lower()}, true, '{{}}'::jsonb, now());")
            stats["svcs"] += 1

        # AI Config
        ai = b.get("ai_config", {})
        L.append(f"  INSERT INTO ai_configurations (id, business_id, enabled, greeting, personality, escalation_enabled, handoff_enabled, language, model_provider, model_name, configuration, created_at) VALUES (gen_random_uuid(), b_id, true, {esc(ai.get('greeting'))}, {esc(ai.get('personality', 'friendly'))}, true, false, 'en', 'openai', 'gpt-4o-mini', '{{}}'::jsonb, now());")

        # Knowledge
        know = b.get("ai_knowledge", [])
        for k in know:
            title, content, cat, pri = k
            L.append(f"  INSERT INTO ai_knowledge_items (id, business_id, title, content, category, priority, is_active, metadata, created_at) VALUES (gen_random_uuid(), b_id, {esc(title)}, {esc(content)}, {esc(cat)}, {pri}, true, '{{}}'::jsonb, now());")
            stats["know"] += 1

        # Photos (is_cover not is_primary)
        photos = b.get("photos", [])
        for i, p in enumerate(photos):
            url, alt, is_cover = p
            L.append(f"  INSERT INTO business_photos (id, business_id, url, alt_text, sort_order, is_cover, created_at) VALUES (gen_random_uuid(), b_id, {esc(url)}, {esc(alt)}, {i}, {str(is_cover).lower()}, now());")
            stats["photos"] += 1

        # Products
        prods = b.get("products", [])
        for i, p in enumerate(prods):
            name_p, desc_p, pt_p, url_p, ptype_p = p
            if pt_p == "free":
                pt_p = "fixed"
            if ptype_p not in ("product", "digital", "gift_card", "service_addon"):
                ptype_p = "product"
            L.append(f"  INSERT INTO business_products (id, business_id, name, description, price_type, url, product_type, sort_order, is_active, created_at) VALUES (gen_random_uuid(), b_id, {esc(name_p)}, {esc(desc_p)}, {esc(pt_p)}, {esc(url_p)}, {esc(ptype_p)}, {i}, true, now());")
            stats["prods"] += 1

        L.append("END $$;")
        L.append("")
        stats["biz"] += 1

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(L))

    print(f"Generated seed.sql:")
    print(f"  {len(cats)} categories")
    print(f"  {stats['biz']} businesses")
    print(f"  {stats['cat_link']} business-category links")
    print(f"  {stats['hrs']} hours entries")
    print(f"  {stats['svcs']} services")
    print(f"  {stats['know']} AI knowledge items")
    print(f"  {stats['photos']} photos")
    print(f"  {stats['prods']} products")
    print(f"  Output: {out_path} ({os.path.getsize(out_path)} bytes)")


if __name__ == "__main__":
    main()
